name: TypeScript Type Check

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run type check
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
